### ISSUE TITLE
Disable Spark UI SSL for spark on yarn

### ISSUE THREAD

**Issue by xuelan** [mapr-emea/mapr-ansible#101]
Spark UI SSL is not needed when running Spark on YARN because encryption is provided by the YARN protocol.
https://mapr.com/docs/home/Spark/ConfigureSparkOnYarn_Encryption.html

**Comment by devproof** [comment]
I think this is only the case, when you run driver in YARN, but ot when driver runs in locally.
I think history server picks it up also.

**Comment by devproof** [comment]
I'm closing ticket, since it is configurable and the config depends on if the driver is running locally or YARN
