### ISSUE TITLE
spyglass_log_password seems not working

### ISSUE THREAD

**Issue by xuelan** [mapr-emea/mapr-ansible#106]
master branch, Redhat 7.5, the variable spyglass_log_password seems not working.

====> With spyglass_log_password: mapr, 
Able to authenticate to kibana with admin:admin
Then, kibana UI showed "authentication exception" to elasticsearch, however, health check of elastic worked with admin:admin

====> With spyglass_log_password: admin, 
Tested admin:admin, no error

Related doc: https://mapr.com/docs/home/AdvancedInstallation/InstallLogging.html

**Comment by devproof** [comment]
Hi Xuelan,

I tested this and it works as expected.
There was another fix related to certificates I fixed last week.
I suspect that it was related to this one.

Can you please retest?

Thanks
Carsten

**Comment by xuelan** [comment]
Hi Carsten,

Just tested branch mapr-6.1.0-MEP-6.0.x, no error anymore in the Kibana UI, but authentication to Kibana/Elasticsearch works still with the defualt password "admin", my change in  spyglass_log_password wasn't taken account by configure.sh

Regards,
Xuelan

**Comment by devproof** [comment]
Can you test on master branch?
The is not in mapr-6.1.0-MEP-6.0.x

**Comment by xuelan** [comment]
It works well on the master branch, possible to have same fix on mapr-6.1.0-MEP-6.0.x?
