### ISSUE TITLE
Drill Config is redundant

### ISSUE THREAD

**Issue by ottensa** [mapr-emea/mapr-ansible#108]
Since at least MapR 6.0.1 MEP 5.0.1 most drill configs are already present in drill-distrib.conf and duplicated by drill-override.conf

**Comment by devproof** [comment]
so should we roll out template using drill-distrib.conf instead of drill-override.conf?

**Comment by ottensa** [comment]
I'd say we identify the differences and apply those in drill-override.
I will work put a concept

**Comment by devproof** [comment]
@ottensa Great thanks. Can you create a pull request once this is fixed?

**Comment by devproof** [comment]
https://mapr.com/docs/61/Drill/drill-config-files.html

drill-contrib.conf is managed by configure.sh. There are no changes made by Ansible.
drill-override.conf overrides all configs from drill-contrib.conf.

So I would keep the current behavior, that we are able to manage all variables without having configure.sh impact of changed template.
