### ISSUE TITLE
handle mfs restart gracefully

### ISSUE THREAD

**Issue by simonputz** [mapr-emea/mapr-ansible#111]
for example, if a customer wants to mfs configuration changes cluster-wide or affecting large number of nodes, which require restart of mfs, we need to take the effect into consideration

suggesting approach (could be slow in large cluster ± 1 minute per node) iteratively, sequentially for all nodes affected:

pre-checks (before putting node in maintenance and before stopping mfs):

Check for Alarms:

cluster alarms, especially cluster full/almost full and too many snapshots

https://mapr.com/docs/61/ReferenceGuide/Cluster-Alarms.html

node alarms like cores present

https://mapr.com/docs/61/ReferenceGuide/NodeAlarms-CorePresentAlarm.html

HB slow

https://mapr.com/docs/61/ReferenceGuide/NodeAlarms-HeartbeatProcessingSlow.html

no disk attached

https://mapr.com/docs/61/ReferenceGuide/NodeAlarms-NoDiskAttachedAlarm.html

disk failure 

https://mapr.com/docs/61/ReferenceGuide/NodeAlarms-DiskFailure.html
e.g. volume alarms like

https://mapr.com/docs/61/ReferenceGuide/VolumeAlarms-DataUnavailable.html
https://mapr.com/docs/61/ReferenceGuide/VolumeAlarms-DataUnderReplicated.html
https://mapr.com/docs/61/ReferenceGuide/VolumeAlarms-CriticallyDegradedECStripes.html
https://mapr.com/docs/61/ReferenceGuide/VolumeAlarms-ECDataNotAvailable.html
https://mapr.com/docs/61/ReferenceGuide/VolumeAlarms-NoNodesInTopology.html

Check container resync, e.g.

https://mapr.com/docs/61/ReferenceGuide/mrconfig-info-containers.html
/opt/mapr/server/mrconfig info containers resync

https://mapr.com/docs/61/ReferenceGuide/mrconfig-cntr-resyncprogress.html
/opt/mapr/server/mrconfig cntr resyncprogress --cids|--volids <id,...>

post-checks (after restarting node):

actual procedure:

0. pre-checks

1. put mode in maintenance mode as per

https://mapr.com/docs/61/AdministratorGuide/t_put_node_into_maintenance_mode.html

maprcli node maintenance -nodes <IP|hostname> -timeoutminutes <minutes>

in scripted approach, depending on the operation, 1 minute could be enough

2. stop warden (important to do this explicitly, otherwise +300 sec delay)

3. perform config changes or other maintenance activity as required

4. take node out of maintenance mode as per

https://mapr.com/docs/61/AdministratorGuide/t_take_node_out_of_maintenance_mode.html

maprcli node maintenance -nodes <IP address> -timeoutminutes 0

5. restart warden (more resilient to use "restart" rather than "start")

service mapr-warden restart

6. post-checks

similar to pre-checks

7. move to next node

**Comment by devproof** [comment]
Available on development branch

**Comment by devproof** [comment]
On master
