### ISSUE TITLE
Tagging playbooks

### ISSUE THREAD

**Issue by dsavell** [mapr-emea/mapr-ansible#114]
Could it be possible to tag playbooks, to be able to skip specific playbooks i.e mapr-configure-repository.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html

Regards,

**Comment by devproof** [comment]
Core and MEP components can run separately by using a playbook from sites folder.
What else except from repository should be excluded? Creating repository is also just an action which takes just some seconds

**Comment by dsavell** [comment]
Hey,

This is just a scenario that helps us with organizational customizations, we noticed that upstream package.mapr.com gets changed as patches are pushed into release folders, this does not help us recreate a immutable / repeatable environments.

This was more a suggestion to help with skipping playbooks and using custom playbooks instead.

Regards,

**Comment by hervenicol** [comment]
Tagging sub-playbooks could help create generic playbooks, and is not a big deal thanks to tag inheritance.


On my side, I was planning to use tags to separate installation and configuration tasks.

The idea was to pre-install images (AMI, GCP boot image or even Docker image), so we can speed-up cluster installation by just running the config tasks.

But this requires much more fine-grained tags.

**Comment by devproof** [comment]
Ok got it.
Ca you propose a structure and what needs to be tagged?

**Comment by devproof** [comment]
Please propose a structure or examples what you want to get tagged.
