### ISSUE TITLE
drill-env.sh configuration does not work for sqlline

### ISSUE THREAD

**Issue by ottensa** [mapr-emea/mapr-ansible#115]
The current drill-env.sh configuration prevents other users than the mapr service user to use sqlline.
This is because it tries to use /opt/mapr/conf/mapruserticket which is only accessible by mapr user.

The current configuration for maprsasl security settings seems redundant, maybe we can just remove those blocks from the drill standalone role.

**Comment by devproof** [comment]
which blocks?

**Comment by devproof** [comment]
Available on development branch

**Comment by devproof** [comment]
On master
