### ISSUE TITLE
Make external shuffle service configurable in spark-defaults.conf

### ISSUE THREAD

**Issue by xuelan** [mapr-emea/mapr-ansible#116]
With the yarn_spark_shuffle variable, external shuffle service is configurable in yanr-site.xml, it will be good to have them in spark-defaults.conf:

{% if yarn_spark_shuffle %}
spark.shuffle.service.enabled true
spark.shuffle.service.port 7337
{% endif %}

**Comment by devproof** [comment]
available on development branc

**Comment by devproof** [comment]
on master
