### ISSUE TITLE
yarn_local_dir_to_maprfs and nm-local-dir volume ambiguity

### ISSUE THREAD

**Issue by okalinin** [mapr-emea/mapr-ansible#120]
When yarn_local_dir_to_maprfs is set to True, mapr-nodemanager-localdir role will create nm-local-dir local volume and set yarn-site.xml config value accordingly.

The issue with it though is that if it gets removed it won't be recreated automatically. That in turn will trigger NM to use /var/mapr volume for localization.

Alternative could be to use subdirectory in 'mapred' local volume which is created by NM startup script automatically.

```
<property>
  <name>yarn.nodemanager.local-dirs</name>
  <value>/mapr/{{ cluster_name }}/var/mapr/local/{{ ansible_fqdn }}/mapred/nm-local-dir</value>
</property>
```

Note : since these volumes are replication factor 1, the need to delete them and clear the alarm in case of disk / HW failure is relatively frequent.

**Comment by devproof** [comment]
Hi Alex,

can you provide a pull request?

Thanks

**Comment by devproof** [comment]
Alex,

the objective is to improve the stability? If it fails at the first run, it does not work with the second?

**Comment by okalinin** [comment]
Hi Carsten,
There is a number of "system volumes" used by various MapR components that are created automatically by MapR component startup scripts. 'mapred' and 'drill' volumes are examples of such volumes. One characteristic of such volume is that they are recreated automatically on component startup in case volume doesn't exists or is in bad condition, which makes handling of volume error easy - just restart the component.

See e.g. /opt/mapr/server/createTTvolume.sh handling of 'mapred' local volume:

```
...
if [ $repfactor -eq 1 -a $rackpath -eq 1 -a $notreadonly -eq 1 -a $mounted -eq 1 -a "n$mountdir" = "n$mountpath" -a $repairedVolume -eq 0 ]; then
        echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume is healthy and mounted at the correct path >> $logFile
        volumeOK=1
        keepExistingContent=1
    else
        if [ $mounted -eq 0 ]; then
            echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume is not mounted >> $logFile
        fi
        if [ "n$mountdir" != "n$mountpath" ]; then
            echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume does not have the expected mountpath, mountpath was $mountdir >> $logFile
        fi
        if [ $repairedVolume -ne 0 ]; then
            echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume cannot be re-used >> $logFile
            cat $commandOutputFile >> $logFile
        fi
        if [ $repfactor -ne 1 ]; then
            echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume does not have the expected replication factor >>$logFile
        fi
        if [ $rackpath -ne 1 ]; then
            echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume does not have the expected rackpath >> $logFile
        fi
        if [ $notreadonly -ne 1 ]; then
            echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume is set to read-only >> $logFile
        fi
        echo `date +"%Y-%m-%d %T"` INFO Pre-existing volume does not have the expected state, removing it >> $logFile
        runCommandWithTimeout 0 60 1 1 "maprcli volume unmount -force 1 -name $vol"
        runCommandWithTimeout 0 60 1 1 "maprcli volume remove -force true -name $vol"
        runCommandWithTimeout 0 60 1 1 "maprcli volume link remove -path $mountpath"
        runCommandWithTimeout 0 60 1 1 "maprcli volume info -name $vol"
        if [ $? -eq 0 ]; then
          echo `date +"%Y-%m-%d %T"` FATAL Issued volume remove API but the volume still exists, exiting >> $logFile
          exit $VOLUME_REMOVAL_FAILED
        fi
        echo `date +"%Y-%m-%d %T"` INFO Removed the pre-existing volume  >> $logFile

        checkPathAndCreateNewTTVolume
    fi
else
    echo `date +"%Y-%m-%d %T"` INFO A pre-existing $LONG_NAME volume could not be found, will try to create one.  >> $logFile
    checkPathAndCreateNewTTVolume
fi
...
```

'nm-local-dir' volumes introduced in mapr-ansible is an exception : it is not recreated automatically at restart of the NM component neither in case it is in bad state/health nor when it is missing. Hence it is required to re-run the playbook manually every time there is an issue with the volume (every time it is hit by bad disk basically).

By re-using 'mapred' volume as explained in initial issue description this problem is eliminated. I will submit PR later today.

**Comment by devproof** [comment]
I can change this, but this is described here, maybe we need to change documentation as well:
https://mapr.com/docs/61/Spark/ConfigureSparkwithNMLocalDirMapR-FS.html?hl=yarn%2Clocal%2Cvolume

**Comment by devproof** [comment]
Changed on master

**Comment by okalinin** [comment]
Thanks Carsten. Indeed, the doc has that issue too. Procedure is correct, but the subtle consequences are not explained. Probably it is meant that user has to extend the procedure/automation on his/her own ...
