### ISSUE TITLE
Remove files from "Fetch keys" after configuration is done

### ISSUE THREAD

**Issue by ottensa** [mapr-emea/mapr-ansible#21]
If you deploy a secured cluster (or add a new node to a secured cluster) some files (cldb.key, maprserverticket, ssl_keystore, ssl_truststore from /opt/mapr/conf) are copied from the first cldb node to the ansible host. From here those files are deployed to the other nodes in order to configure them properly. After you deployed the keys and configured the nodes those keys should be removed from the ansible host.

**Comment by devproof** [comment]
@ottensa can you provide pull request?

**Comment by devproof** [comment]
Done on devmapr61 branch
