### ISSUE TITLE
TASK [../roles/mapr-hive-cli-install : Create maprfs:///apps]

### ISSUE THREAD

**Issue by brazzaville** [mapr-emea/mapr-ansible#25]
The playbook site-cluster failed on the following error: 
fatal: [mapr03]: FAILED! => {"changed": true, "cmd": "hadoop fs -mkdir -p /apps", "delta": "0:00:04.294720", "end": "2018-04-01 01:46:55.671684", "msg": "non-zero return code", "rc": 1, "start": "2018-04-01 01:46:51.376964", "stderr": "mkdir: failure to login: Unable to obtain MapR credentials"
Please help me to fix it

**Comment by devproof** [comment]
Default ticket should be taken for creation /opt/mapr/conf/mapruserticket.
If this file does not exist, something went wrong during startup, I guess this is related to your CLDB issue.

**Comment by devproof** [comment]
Please provide feedback.

**Comment by devproof** [comment]
closed, because requirement is not clear and no feedback was provided.
