### ISSUE TITLE
Wait for CLDB Timeout 

### ISSUE THREAD

**Issue by brazzaville** [mapr-emea/mapr-ansible#26]
TASK [../roles/mapr-configure-warden-cldb-restart : Wait for CLDB] **********************************************************************************************************
fatal: [192.168.2.60]: FAILED! => {"changed": false, "elapsed": 1800, "msg": "Timeout when waiting for search string CLDB State change \\:\\ RUNNING|CLDBShutdown\\:\\ license not found for CLDB HA|Becoming Slave Thread in /opt/mapr/logs/cldb.log"}

**Comment by devproof** [comment]
This means your CLDB didn't start properly. Please check log files on all nodes:
/opt/mapr/logs/cldb.log
/opt/mapr/logs/mfs.log-3

**Comment by devproof** [comment]
could you solve it?

**Comment by devproof** [comment]
@brazzaville please provide feedback.

**Comment by devproof** [comment]
closed, because requirement is not clear and no feedback was provided.
