### ISSUE TITLE
skipping: no hosts matched

### ISSUE THREAD

**Issue by brazzaville** [mapr-emea/mapr-ansible#29]
When 
PLAY [Uninstall MCS]
PLAY [Uninstall YARN Resource Manager]
PLAY [Uninstall History Server]
PLAY [Uninstall MapR-Fileserver]...

**Comment by devproof** [comment]
yes this is expected.
What is the error or request?

**Comment by devproof** [comment]
@brazzaville please provide feedback.

**Comment by devproof** [comment]
closed, because requirement is not clear and no feedback was provided.
