### ISSUE TITLE
Feature Request - Support for different Kerberos principals across components

### ISSUE THREAD

**Issue by HariSekhon** [mapr-emea/mapr-ansible#4]
Feature Request for this Ansible repo to support different Kerberos principals + keytabs for different components such as Yarn, Drill, Hive, HBase, MapR-DB etc rather than just 1 cluster-wide keytab.

**Comment by devproof** [comment]
is it really required to have different Kerberos Principals? What is the requirement?

**Comment by HariSekhon** [comment]
To elaborate, if even a single non-core component were to be compromised, for example a bug in Oozie UI or Yarn UI then this would expose the mapr superuser keytab which would completely compromise all the data in the MapR-FS cluster.

Right now this needs additional support from MapR core engineering because all processes are run as the mapr OS user instead of separate users as you would normally see on other platforms, which means that even with separate keytabs a compromise of any single component could allow file access to the other keytabs anyway, so we need not just separate keytabs but also separate users to run each component and restrictive file permissions to keytabs restricting each user to be able to access only their own keytab.

Sorry, I know this isn't a quick fix and requires support from MapR core engineering, but I think we should leave this open until MapR fix the core.
