### ISSUE TITLE
SUSE install zypper unsigned repository

### ISSUE THREAD

**Issue by muove** [mapr-emea/mapr-ansible#45]
Following error will take place on Suse (6 nodes example):
TASK [../roles/mapr-core-install : Install mapr-core] ***************************************************************************************************************************************
failed: [ip-172-.ec2.internal] (item=mapr-compat-suse) => {"changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+mapr-compat-suse"], "item": "mapr-compat-suse", "msg": "No provider of '+mapr-compat-suse' found.", "rc": 104, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<prompt id=\"11\">\n<text>File &apos;repomd.xml&apos; from repository &apos;maprecosystem&apos; is unsigned, continue?</text>\n<option value=\"yes\" desc=\"\"/>\n<option default=\"1\" value=\"no\" desc=\"\"/>\n</prompt>\n<message type=\"error\">Repository &apos;maprecosystem&apos; is invalid.\n[maprecosystem|http://package.mapr.com/releases/MEP/MEP-4.1.0//suse/] Valid metadata not found at specified URL\nPlease check if the URIs defined for this repository are pointing to a valid repository.\n</message>\n<message type=\"warning\">Skipping repository &apos;maprecosystem&apos; because of the above error.</message>\n<prompt id=\"11\">\n<text>File &apos;repomd.xml&apos; from repository &apos;maprtech&apos; is unsigned, continue?</text>\n<option value=\"yes\" desc=\"\"/>\n<option default=\"1\" value=\"no\" desc=\"\"/>\n</prompt>\n<message type=\"error\">Repository &apos;maprtech&apos; is invalid.\n[maprtech|http://package.mapr.com/releases/v6.0.0/suse/] Valid metadata not found at specified URL\nPlease check if the URIs defined for this repository are pointing to a valid repository.\n</message>\n<message type=\"warning\">Skipping repository &apos;maprtech&apos; because of the above error.</message>\n<message type=\"error\">Some of the repositories have not been refreshed because of an error.</message>\n<message type=\"error\">No provider of &apos;+mapr-compat-suse&apos; found.</message>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<prompt id=\"11\">", "<text>File &apos;repomd.xml&apos; from repository &apos;maprecosystem&apos; is unsigned, continue?</text>", "<option value=\"yes\" desc=\"\"/>", "<option default=\"1\" value=\"no\" desc=\"\"/>", "</prompt>", "<message type=\"error\">Repository &apos;maprecosystem&apos; is invalid.", "[maprecosystem|http://package.mapr.com/releases/MEP/MEP-4.1.0//suse/] Valid metadata not found at specified URL", "Please check if the URIs defined for this repository are pointing to a valid repository.", "</message>", "<message type=\"warning\">Skipping repository &apos;maprecosystem&apos; because of the above error.</message>", "<prompt id=\"11\">", "<text>File &apos;repomd.xml&apos; from repository &apos;maprtech&apos; is unsigned, continue?</text>", "<option value=\"yes\" desc=\"\"/>", "<option default=\"1\" value=\"no\" desc=\"\"/>", "</prompt>", "<message type=\"error\">Repository &apos;maprtech&apos; is invalid.", "[maprtech|http://package.mapr.com/releases/v6.0.0/suse/] Valid metadata not found at specified URL", "Please check if the URIs defined for this repository are pointing to a valid repository.", "</message>", "<message type=\"warning\">Skipping repository &apos;maprtech&apos; because of the above error.</message>", "<message type=\"error\">Some of the repositories have not been refreshed because of an error.</message>", "<message type=\"error\">No provider of &apos;+mapr-compat-suse&apos; found.</message>", "</stream>"]}

root cause: zypper asks user in case of repository unsigned

**Comment by devproof** [comment]
Made GPG check configurable in group_vars/all in devmapr61 branch
