### ISSUE TITLE
Disable the Transparent Huge Pages (THP) feature in the Linux kernel

### ISSUE THREAD

**Issue by xuelan** [mapr-emea/mapr-ansible#54]
MapR recommends disabling the Transparent Huge Pages (THP) feature in the Linux kernel.
https://mapr.com/docs/home/AdvancedInstallation/PreparingEachNode-infrastructure.html

**Comment by devproof** [comment]
This won't be implemeneted, since it is not directly related to MapR.
This change requires a Grub configuration change and if done wrong, it can break the boot process.
Difficult to say if it always same on all images, furthermore it might be different for Suse and Ubuntu.

**Comment by bmillemathias** [comment]
> This change requires a Grub configuration change
It can be disable at runtime using /sys/kernel/mm/redhat_transparent_hugepage/enabled (for RedHat), but true that can be implemented as a separate role
